index/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.views.generic import ListView
from django.utils import timezone
from index import views
from index.models import WritePost, CodePost, MusicPost, MiscPost
from index.views import code, writing, music, misc

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about_index'),
    url(r'^(?P<post_type_name>[a-z]{0,10})/(?P<post_id>\d+)/details/$', views.details,
        name='details'),
    # Code pages *******************************************************
    url(r'^code/$',
       ListView.as_view(
           queryset=CodePost.objects.filter(pub_date__lte=timezone.now).order_by('-pub_date')[:5],
           context_object_name='latest_code_post_list',
           template_name='code/index.html'),
       name='code_index'),
    url(r'^code/history/$', views.history, {'post_type': code}, name='code_history'),
    # Writing pages ***************************************************
    url(r'^writing/$',
       ListView.as_view(
           queryset=WritePost.objects.filter(pub_date__lte=timezone.now).order_by('-pub_date')[:5],
           context_object_name='latest_write_post_list',
           template_name='writing/index.html'),
       name='write_index'),
    url(r'^writing/history/$', views.history, {'post_type': writing}, name='write_history'),
    # Music pages ******************************************************
    url(r'^music/$',
       ListView.as_view(
           queryset=MusicPost.objects.filter(pub_date__lte=timezone.now).order_by('-pub_date')[:5],
           context_object_name='latest_music_post_list',
           template_name='music/index.html'),
       name='music_index'),
    url(r'^music/history/$', views.history, {'post_type': music}, name='music_history'),
    # Misc pages ******************************************************
    url(r'^misc/$',
        ListView.as_view(
            queryset=MiscPost.objects.filter(pub_date__lte=timezone.now).order_by('-pub_date')[:5],
            context_object_name='latest_misc_post_list',
            template_name='misc/index.html'),
        name='misc_index'),
    url(r'^misc/history/$', views.history, {'post_type': misc}, name='misc_history'),
   )

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

thiscityhums/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'thiscityhums.views.home', name='home'),
    # url(r'^thiscityhums/', include('thiscityhums.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('index.urls', namespace="site_index")),
)

templates/misc/details.html
<!DOCTYPE html>
{% load url from future %}
{% include 'common/header.html' %}
<!-- Navbar ================================================== -->
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="{% url 'site_index:about_index' %}">william southers</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="">
                        <a href="{% url 'site_index:index' %}">Home</a>
                    </li>
                    <li class="">
                        <a href="{% url 'site_index:code_index' %}">Code</a>
                    </li>
                    <li class="">
                        <a href="{% url 'site_index:write_index' %}">Writing</a>
                    </li>
                    <li class="">
                        <a href="{% url 'site_index:music_index' %}">Music</a>
                    </li>
                    <li class="active">
                        <a href="{% url 'site_index:misc_index' %}">Misc</a>
                    </li>
                    <li class="">
                        <a href="{% url 'site_index:about_index' %}">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% load url from future %}
<div class="container">
    {% include 'common/post_details.html' %}
</div>
{% include 'common/footer.html' %}

templates/misc/index.html
<!DOCTYPE html>
{% load url from future %}
{% include 'common/header.html' %}
<!-- Navbar ================================================== -->
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="{% url 'site_index:about_index' %}">william southers</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="">
                        <a href="{% url 'site_index:index' %}">Home</a>
                    </li>
                    <li class="">
                        <a href="{% url 'site_index:code_index' %}">Code</a>
                    </li>
                    <li class="">
                        <a href="{% url 'site_index:write_index' %}">Writing</a>
                    </li>
                    <li class="">
                        <a href="{% url 'site_index:music_index' %}">Music</a>
                    </li>
                    <li class="active">
                        <a href="{% url 'site_index:misc_index' %}">Misc</a>
                    </li>
                    <li class="">
                        <a href="{% url 'site_index:about_index' %}">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="marketing">
        <div class="row-fluid">
            <h1>
                last 5 miscellaneous posts<span><h3><a href="{% url 'site_index:misc_history' %}">see all</a></h3></span>
            </h1>
        </div>
    </div>
    <div class="row-fluid">
        {% if latest_misc_post_list %}
            <table class="table table-hover">
                {% for post in latest_misc_post_list %}
                    <tr>
                        <td>
                            <h2><a href="{% url 'site_index:details' 'misc' post.id %}">{{ post.title }}</a> - published: {{ post.pub_date }}</h2>
                            <p>{{ post.abstract|safe }}</p>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <p>No posts available.</p>
        {% endif %}
    </div>
</div>
{% include 'common/footer.html' %}